name: Vulnerability
on:
  schedule:
    - cron: '0 1 * * 6'
  workflow_dispatch:
jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install the project
        run: uv sync --all-groups --all-extras --dev
      - name: Run pip-audit and save result
        run: uvx pip-audit -f markdown > audit-result.txt
      - name: Create issue if vulnerabilities are found
        if: failure()
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ $(wc -l < audit-result.txt) -gt 1 ]; then
            gh issue create \
              --title "Vulnerabilities found in pip-audit - $(date "+%Y-%m-%d %H:%M:%S %Z")" \
              --body "$(cat audit-result.txt)" \
              --label "enhancement"
          fi
